apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: cassandra-database
 labels:
   app: cassandra
spec:
 replicas: 2
 selector:
   matchLabels:
     app: cassandra
 template:
   metadata:
     labels:
       app: cassandra
   spec:
     securityContext:
       runAsUser: 0
     containers:
     - name: cassandradb
       image: bitnami/cassandra:latest
       ports:
       - containerPort: 9042
         name: cassandra
       env:
       - name: CASSANDRA_USERNAME
         value: "myuser"
       - name: CASASNDRA_PASSWORD
         value: "mypassword"
       volumeMounts:
       - name: cassandra-storage
         mountPath: /bitnami/cassandra
     volumes:
     - name: cassandra-storage
       persistentVolumeClaim:
         claimName: cassandra-pv-claim
      
---
apiVersion: v1
kind: Service
metadata:
 name: cassandra-service
spec:
 selector:
   app: cassandra
 ports:
   - protocol: TCP
     port: 7000
     targetPort: 7000
