apiVersion: v1
kind: StatefulSet
metadata:
  name: cassandra-database
  labels:
    app: cassandra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandradb
        image: cassandra:latest
        ports:
        - containerPort: 9042
          name: cassandra
      volumeMounts:
        - name: cassandra-storage
          mountPath: /var/lib/cassandra
      volumes:
      - name: cassandra-storage
        PersistentVolumeClaim:
        claimName: cassandra-pv-claim
          
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042

